### ISSUE TITLE
Installer task fails behind company proxy

### ISSUE THREAD

**Issue by KristofKuli** [charleszipp/azure-pipelines-tasks-terraform#320]
Terraform Installer task throws timeout during pipeline execution. All the agents are behind company proxy. Could that be the issue? Regarding the source code, maybe fetch is not able to recognize the proxy settings?
https://github.com/jason-johnson/azure-pipelines-tasks-terraform/blob/c1c99a58f820682edf3b4a095b613059722f46d9/tasks/terraform-installer/src/installer.ts#L17

**Comment by piizei** [comment]
Hi @KristofKuli 
Node-proxy should rely on env variables HTTP_PROXY or HTTPS_PROXY. Have you tried these?

**Comment by KristofKuli** [comment]
Hi Petteri,

HTTP_PROXY and HTTPS_PROXY are both set on the agents, furthermore I have also defined them directly in the Terraform task, but it still fails.

**Comment by piizei** [comment]
Would you know if the download works directly from example  from https://releases.hashicorp.com/terraform/1.3.7/terraform_1.3.7_linux_arm.zip with wget/curl? Sometimes proxies also block binary download.

**Comment by KristofKuli** [comment]
Curl returned HTTP 200, so that works.

**Comment by KristofKuli** [comment]
Update: we checked on Azure Pipelines pool, which hosted by MS and the download work there. Furthermore, the customer also has his own VM scale set in Azure, where the proxy is not set and pipeline is successful.

**Comment by KristofKuli** [comment]
Is there any update on this? We are still believe the issue is that the fetch is not able to recognize the proxy settings. A similar task (Node Installer) works perfectly fine, so we don't think the issue is with the proxy.

**Comment by jason-johnson** [comment]
@KristofKuli There is a PR in flight right now that should resolve this issue

**Comment by KristofKuli** [comment]
Thank you for the fix! Could you please let me know when this will be available on the Marketplace to update?

**Comment by KristofKuli** [comment]
Any update on this? I have tested the task, but it is still failing with timeout.

**Comment by jason-johnson** [comment]
@KristofKuli The task has now been released, if you update to the newest version is it still failing?

**Comment by jason-johnson** [comment]
Reopening until fix is verified

**Comment by jason-johnson** [comment]
Possibly related to #19

**Comment by KristofKuli** [comment]
Specifying the exact version solved the issue. Thank you.
